---
# slurm/tasks/configure.yml
#
- name: systemd
  ansible.builtin.template:
    dest: /etc/systemd/system/slurmd.service
    mode: 0644
    src: slurmd.service.j2
  notify:
    - reload daemon
    - restart slurmd

- name: etc/slurm confdir
  ansible.builtin.file:
    group: root
    mode: 0755
    owner: root
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ slurm_confdir }}"
    - "{{ slurm_confdir }}/epilog.d"
    - "{{ slurm_confdir }}/prolog.d"
    - "{{ slurm_confdir }}/plugstack.conf.d"

- name: configure
  ansible.builtin.template:
    dest: "{{ slurm_confdir }}/slurm.conf"
    lstrip_blocks: true
    mode: 0644
    src: slurm.conf.j2
  notify:
    - restart slurmd

- name: environment
  ansible.builtin.copy:
    content: |
      SLURM_CONF="{{ slurm_confdir }}/slurm.conf"
    dest: /etc/profile.d/slurm.sh
    mode: 0644

- name: configure cgroup
  ansible.builtin.template:
    dest: "{{ slurm_confdir }}/cgroup.conf"
    lstrip_blocks: true
    mode: 0644
    src: cgroup.conf.j2
  notify:
    - restart slurmd
- name: cgroup_allowed_devices_file.conf
  ansible.builtin.copy:
    content: "{{ slurm_cgroup_allowed_devices }}"
    dest: "{{ slurm_confdir }}/cgroup_allowed_devices_file.conf"
    mode: 0644
  notify:
    - restart slurmd

- name: job_submit.lua
  ansible.builtin.copy:
    dest: "{{ slurm_confdir }}/job_submit.lua"
    group: root
    mode: 0755
    owner: root
    src: "{{ playbook_dir }}/{{ slurm_job_submit_lua_path }}"
  notify:
    - restart slurmd
  when:
    - slurm_job_submit_lua_path is defined
    - slurm_job_submit_lua_path |length >0

- name: epilog
  ansible.builtin.copy:
    dest: "{{ slurm_confdir }}/epilog.d/{{ item |basename }}"
    mode: 0755
    src: "{{ playbook_dir }}/{{ item }}"
  when:
    - slurm_epilog is defined
    - slurm_epilog |length >0
  with_items:
    - "{{ slurm_epilog }}"

- name: prolog
  ansible.builtin.copy:
    dest: "{{ slurm_confdir }}/prolog.d/{{ item |basename }}"
    mode: 0755
    src: "{{ playbook_dir }}/{{ item }}"
  when:
    - slurm_prolog is defined
    - slurm_prolog |length >0
  with_items:
    - "{{ slurm_prolog }}"

# SPANK
# https://slurm.schedmd.com/spank.html
- name: etc/slurm/plugstack.conf
  ansible.builtin.template:
    dest: "{{ slurm_confdir }}/plugstack.conf"
    mode: 0644
    src: plugstack.conf.j2
  notify:
    - restart slurmd

# https://github.com/hpc2n/spank-private-tmp
- name: private-tmpdir
  block:
    - name: private-tmpdir
      ansible.builtin.template:
        dest: "{{ slurm_confdir }}/plugstack.conf.d/private-tmpdir.conf"
        mode: 0644
        src: plugstack.conf.d/private-tmpdir.j2

    - name: private-tmpdir epilog
      ansible.builtin.template:
        dest: "{{ slurm_confdir }}/epilog.d/private-tmpdir.conf"
        mode: 0755
        src: plugstack.conf.d/private-tmpdir-epilog.j2
  when:
    - slurm_private_tmpdir is defined
    - slurm_private_tmpdir |length >0

- name: etc/slurm/plugstack.conf.d
  ansible.builtin.copy:
    dest: "{{ slurm_confdir }}/plugstack.conf.d/{{ item |basename }}"
    mode: 0644
    src: "{{ playbook_dir }}/{{ item }}"
  with_items:
    - "{{ slurm_plugstack_conf }}"
  when:
    - slurm_plugstack_conf is defined
    - slurm_plugstack_conf |length >0

- name: enable service
  ansible.builtin.service:
    enabled: true
    name: "{{ slurm_service }}"
